name: Node.js CI

on:
  pull_request:
    branches:
      - main # Trigger this workflow on PRs targeting the main branch
  push:
    branches:
      - main # Optional: Trigger on pushes to the main branch (e.g., after merging)

jobs:
  build:
    runs-on: ubuntu-latest # The OS for the CI pipeline

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Checkout the code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the version of Node.js (adjust as needed)

      - name: Install dependencies
        run: npm ci # Install dependencies with npm ci (for CI environments)

      - name: Run tests
        run: npm test # Run tests (assumes jest is set up)

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: ./test-results # Customize if you have test result files you want to upload
